CREATE DATABASE first_lesson
GO
USE first_lesson
GO
CREATE TABLE authors
(
id BIGINT IDENTITY(1,1) PRIMARY KEY,
name NVARCHAR(20) NOT NULL,
surname NVARCHAR(30) NOT NULL,
created_at datetime2 DEFAULT GETDATE()
);